name: Deploy GitHub Pages

on:
  push:
    paths:
      [
        'src/**',
        'package.json',
        'tsconfig.json',
        'bun.lockb',
        '.github/workflows/github-pages.yml'
      ]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bun run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'build'
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    
